language: scala
sudo: true
jdk:
  - oraclejdk8
python: "2.6"
install:
  - sudo pip install inspyred
  - sudo pip install argparse

# only build PRs for the following branches (not all branch pushes)
branches:
  only:
    - master
    - tuning_20190221

